//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer gObjectConstants
// {
//
//   struct ObjectConstants
//   {
//       
//       float4x4 gWorlViewProj;        // Offset:    0
//       uint matIndex;                 // Offset:   64
//       float gTime;                   // Offset:   68
//       float4 gColor;                 // Offset:   80
//
//   } gObjectConstants;                // Offset:    0 Size:    96
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      ID      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- ------- -------------- ------
// gObjectConstants                  cbuffer      NA          NA     CB0            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// COLOR                    0   xyzw        0     NONE   float   xyzw
// POSITION                 0   xyz         1     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// COLOR                    0   xyzw        1     NONE   float   xyzw
//
vs_5_1
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB0[0:0][4], immediateIndexed, space=0
dcl_input v0.xyzw
dcl_input v1.xyz
dcl_output_siv o0.xyzw, position
dcl_output o1.xyzw
dcl_temps 2
//
// Initial variable locations:
//   v0.x <- vin.Color.x; v0.y <- vin.Color.y; v0.z <- vin.Color.z; v0.w <- vin.Color.w; 
//   v1.x <- vin.PosL.x; v1.y <- vin.PosL.y; v1.z <- vin.PosL.z; 
//   o1.x <- <VS return value>.Color.x; o1.y <- <VS return value>.Color.y; o1.z <- <VS return value>.Color.z; o1.w <- <VS return value>.Color.w; 
//   o0.x <- <VS return value>.PosH.x; o0.y <- <VS return value>.PosH.y; o0.z <- <VS return value>.PosH.z; o0.w <- <VS return value>.PosH.w
//
#line 33 "C:\Users\myc\Desktop\LearnDirectX12\shader\box.hlsl"
mov r0.xyz, v1.xyzx
mov r0.w, l(1.000000)
dp4 r1.x, r0.xyzw, CB0[0][0].xyzw  // r1.x <- vout.PosH.x
dp4 r1.y, r0.xyzw, CB0[0][1].xyzw  // r1.y <- vout.PosH.y
dp4 r1.z, r0.xyzw, CB0[0][2].xyzw  // r1.z <- vout.PosH.z
dp4 r1.w, r0.xyzw, CB0[0][3].xyzw  // r1.w <- vout.PosH.w

#line 38
mov r0.xyzw, v0.xyzw  // r0.x <- vout.Color.x; r0.y <- vout.Color.y; r0.z <- vout.Color.z; r0.w <- vout.Color.w

#line 39
mov o0.xyzw, r1.xyzw
mov o1.xyzw, r0.xyzw
ret 
// Approximately 10 instruction slots used
